routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('empleados','EmpleadoController')->names('empleados');
Route::resource('empresas','EmpresaController')->names('empresas');

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
	protected $fillable =
					[
						'nombre_empleado','apellido_empleado','direccion_empleado','telefono_empleado','empresa_id','activo'
					];
    public function empresa(){
    	return $this->belongsTo(Empresa::class);
    }
    public function activate(){
        $this->update(['activo' => false]);
    }
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use App\Empleado;
use \App\Empresa;
use Illuminate\Http\Request;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       /*return view('empleados.views.index',[
            'data' => Empleado::with('empresa')->latest()->get(),
        ]);*/
        return view('empleados.views.index',[
            'empleados' => Empleado::with('empresa')->where('activo','1')->latest()->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleados.views.create',[
            'empresas' => Empresa::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request,[
            'nombre_empleado' => 'required',
            'apellido_empleado' => 'required',
            'direccion_empleado' => 'required',
            'telefono_empleado' => 'required',
            'empresa_id' => 'required',
        ]);
        Empleado::create($validate);
        return redirect()->route('empleados.index')->withFlash('Dato guardado exitosamnete');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function show(Empleado $empleado)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function edit(Empleado $empleado)
    {
        return view('empleados.views.edit',[
            'empresa' => Empresa::pluck('nombre_empresa','id'),
            'empleado' => $empleado
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Empleado $empleado)
    {
        if($request->ajax()){
            $validate = $this->validate($request,[
                'nombre_empleado' => 'required',
                'apellido_empleado' => 'required',
                'direccion_empleado' => 'required',
                'telefono_empleado' => 'required',
                'empresa_id' => 'required',
            ]);

            $empleado->update($validate);
            return response()->json([
                "mensaje" => "datos actualizados has sido actualizados con exito redirigir a <a href='http://www.directenglish.local/empleados'>Home</>"
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empleado $empleado)
    {
         $empleado->activate();
        return redirect()->route('empleados.index')->withFlash("El registro ha sido eliminado con exito");
    }
}

resources/views/empleados/views/create.blade.php
 @extends('empleados.layout')
 @section('content')
 <div class="alert alert-primary alert-dismissible fade show data-alert" role='alert' style="display: none;">
						{{-- {{ session('flash') }} --}}
						<button type="button" class="close" data-dismiss="alert" aria-label="close" >
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
 <form method="POST" action="{{ route('empleados.store') }}" id="saveforms">
  @csrf
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">

	      <h4 class="modal-title" id="myModalLabel">Creacion de un registro</h4>
	    </div>
	    <div class="modal-body">
	      <div class="form-group {{ $errors->has('nombre_empleado') ? 'has-error' : '' }}">
	        <input id="nombre" class="form-control" type="text" name="nombre_empleado" placeholder="ingrese el nombre del empleado"
	        value="{{ old('nombre_empleado')}}" autofocus >
	        {!! $errors->first('nombre_empleado', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('apellido_empleado') ? 'has-error' : '' }}">
	        <input id="apellido" class="form-control" type="text" name="apellido_empleado" placeholder="ingrese el apellido del empleado"
	        value="{{ old('apellido_empleado')}}" autofocus >
	        {!! $errors->first('apellido_empleado', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('direccion_empleado') ? 'has-error' : '' }}">
	        <input id="direccion_empleado" class="form-control" type="text" name="direccion_empleado" placeholder="ingrese la direccion del empleado"
	        value="{{ old('direccion_empleado')}}" autofocus >
	        {!! $errors->first('direccion_empleado', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('telefono_empleado') ? 'has-error' : '' }}">
	        <input id="telefono_empleado" class="form-control" type="text" name="telefono_empleado" placeholder="ingrese el telefono del empleado"
	        value="{{ old('telefono_empleado')}}" autofocus >
	        {!! $errors->first('telefono', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('empresa_id') ? 'has-error' : '' }}">
	      	<label>Seleccione la empresa</label>
	        <select class="form-control" name="empresa_id">
	        	@foreach($empresas as $empresa)
	        		<option value="{{ $empresa->id }}">
	        			{{ $empresa->nombre_empresa }}
	        		</option>
	        	@endforeach
	        </select>
	      </div>
	    </div>
	    <div class="modal-footer">
	      <button id="createpost"  onclick="saveproject()"  class="btn btn-primary">Crear publicacion</button>
	    </div>
	  </div>
	</div>
</form>
@endsection

resources/views/empleados/views/edit.blade.php
 @extends('empleados.layout')
 @section('content')
 <form method="POST" action="#" id="saveformsupdate">
  @csrf
  @method('PUT')
  <div class="alert alert-primary alert-dismissible fade show data-alert" role='alert' style="display: none;" >
		<button type="button" class="close" data-dismiss="alert" aria-label="close" >
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">

	      <h4 class="modal-title" id="myModalLabel">Editar un proyecto</h4>
	    </div>
	    <div class="modal-body">
	      <div class="form-group {{ $errors->has('nombre_empleado') ? 'has-error' : '' }}">
	        <input id="nombre" class="form-control" type="text" name="nombre_empleado" placeholder="ingrese el nombre del empleado"
	        value="{{ old('nombre_empleado',$empleado->nombre_empleado)}}" autofocus >
	        {!! $errors->first('nombre_empleado', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('apellido_empleado') ? 'has-error' : '' }}">
	        <input id="apellido" class="form-control" type="text" name="apellido_empleado" placeholder="ingrese el apellido del empleado"
	        value="{{ old('apellido_empleado',$empleado->apellido_empleado)}}" autofocus >
	        {!! $errors->first('apellido_empleado', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('direccion_empleado') ? 'has-error' : '' }}">
	        <input id="direccion_empleado" class="form-control" type="text" name="direccion_empleado" placeholder="ingrese la direccion del empleado"
	        value="{{ old('direccion_empleado',$empleado->direccion_empleado)}}" autofocus >
	        {!! $errors->first('direccion_empleado', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('telefono_empleado') ? 'has-error' : '' }}">
	        <input id="telefono_empleado" class="form-control" type="text" name="telefono_empleado" placeholder="ingrese el telefono del empleado"
	        value="{{ old('telefono_empleado',$empleado->telefono_empleado)}}" autofocus >
	        {!! $errors->first('telefono', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('empresa_id') ? 'has-error' : '' }}">
	      	<label>Seleccione la empresa</label>
	        <select class="form-control" name="empresa_id">
	        	@foreach($empresa as $id =>$name)
	        		<option value="{{ $id }}" {{$id ==old('empresa_id',$empleado->empresa_id)  ? 'selected' : ''}}>
	        			{{ $name}}
	        		</option>
	        	@endforeach
	        </select>
	      </div>
	    </div>
	    <div class="modal-footer">
	      <button  class="btn btn-primary" onclick="actualizar({{$empleado->id}})">Actualizar publicacion</button>
	    </div>
	  </div>
	</div>
</form>
@endsection{{-- {{$project->id}} como parametro en el evento --}}

resources/views/empleados/views/index.blade.php
@extends('empleados.layout')
@section('content')
	<div class="container">
		<div class="row">
              @if(session('flash'))
					<div class="alert alert-primary alert-dismissible fade show data-alert" role='alert' >
						{{ session('flash') }}
						<button type="button" class="close" data-dismiss="alert" aria-label="close" >
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				@endif
			<div class="mx-auto">
				CONTENIDO DE LA TABLA EMPLEADOS
			</div>
		</div>
		<div class="row">
			<div class="mx-auto">
				<a  href="{{ route('empleados.create')}}">Crear un empleado</a>
				<table class="table">
					<tr>
						<td>ID_EMPLEADO</td>
						<td>NOMBRE</td>
						<td>APELLIDO</td>
						<td>DIRECCION</td>
						<td>TELEFONO</td>
						<td>EMPRESA</td>
						<td>ACCIONES</td>
					</tr>
					@foreach($empleados as $empleado)
						<tr>
							<td>{{$empleado->id}}</td>
							<td>{{$empleado->nombre_empleado}}</td>
							<td>{{$empleado->apellido_empleado}}</td>
							<td>{{$empleado->direccion_empleado}}</td>
							<td>{{$empleado->telefono_empleado}}</td>
							<td>{{$empleado->empresa->nombre_empresa}}</td>
							<td>
								<a class="btn btn-xs  btn-primary" href="{{ route('empleados.edit',$empleado) }}">Editar</a>

								/
								<form id="saveformdelete" action="{{ route('empleados.destroy',$empleado) }}" method="POST" style="display: inline;">
				                @csrf @method('DELETE')
				                <button onclick="return confirm('Esta seguro de eliminar la prublicacion ?')"class="btn btn-xs  btn-danger">Eliminar</button>
				              </form>
							</td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
@endsection