routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('empleados','EmpleadoController')->names('empleados');
Route::resource('empresas','EmpresaController')->names('empresas');

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
	protected $fillable =
					[
						'nombre_empleado','apellido_empleado','direccion_empleado','telefono_empleado','empresa_id','activo'
					];
    public function empresa(){
    	return $this->belongsTo(Empresa::class);
    }
    public function activate(){
        $this->update(['activo' => false]);
    }
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use App\Empleado;
use \App\Empresa;
use Illuminate\Http\Request;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       /*return view('empleados.views.index',[
            'data' => Empleado::with('empresa')->latest()->get(),
        ]);*/
        return view('empleados.views.index',[
            'empleados' => Empleado::with('empresa')->where('activo','1')->latest()->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleados.views.create',[
            'empresas' => Empresa::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request,[
            'nombre_empleado' => 'required',
            'apellido_empleado' => 'required',
            'direccion_empleado' => 'required',
            'telefono_empleado' => 'required',
            'empresa_id' => 'required',
        ]);
        Empleado::create($validate);
        return redirect()->route('empleados.index')->withFlash('Dato guardado exitosamnete');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function show(Empleado $empleado)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function edit(Empleado $empleado)
    {
        return view('empleados.views.edit',[
            'empresa' => Empresa::pluck('nombre_empresa','id'),
            'empleado' => $empleado
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Empleado $empleado)
    {
        if($request->ajax()){
            $validate = $this->validate($request,[
                'nombre_empleado' => 'required',
                'apellido_empleado' => 'required',
                'direccion_empleado' => 'required',
                'telefono_empleado' => 'required',
                'empresa_id' => 'required',
            ]);

            $empleado->update($validate);
            return response()->json([
                "mensaje" => "datos actualizados has sido actualizados con exito redirigir a <a href='http://www.directenglish.local/empleados'>Home</>"
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empleado $empleado)
    {
         $empleado->activate();
        return redirect()->route('empleados.index')->withFlash("El registro ha sido eliminado con exito");
    }
}

resources/views/empleados/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">﻿
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="#">
                    CRUD CON LARAVEL, AJAX Y JSON <a href="{{ route('empresas.index')}}">Administrar Empresas</a>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script type="text/javascript">

        function actualizar(id){
            event.preventDefault()
               var datas = $("#saveformsupdate").serialize();
               var token = $('meta[name="csrf-token"]').attr('content');
               $.ajax({
                url: 'http://www.directenglish.local/empleados/'+id,
                headers: {'X-CSRF-TOKEN':token},
                type: 'PUT',
                dataType: 'json',
                data : datas,
                success:function(data){
                    var message = JSON.stringify(data);
                    var mesage_parse = JSON.parse(message);
                    $(".alert-dismissible ").html(" "+mesage_parse.mensaje+" ");
                    $(".alert-dismissible ").show();
                }
            });
        }
    </script>
</body>
</html>