routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('empleados','EmpleadoController')->names('empleados');
Route::resource('empresas','EmpresaController')->names('empresas');

app/Empresa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empresa extends Model
{
	protected $fillable =
					[
						'nombre_empresa','direccion_empresa','telefono_empresa','activo'
					];
    public function empleados(){
    	return $this->hasMany(Empleado::class);
    }
    public function activate(){
        $this->update(['activo' => false]);
    }
}

app/Http/Controllers/EmpresaController.php
<?php

namespace App\Http\Controllers;

use App\Empresa;
use Illuminate\Http\Request;

class EmpresaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('empresas.views.index',[
            'empresas' => Empresa::with('empleados')->where('activo','1')->latest()->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('empresas.views.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request,[
            'nombre_empresa' => 'required',
            'direccion_empresa' => 'required',
            'telefono_empresa' => 'required',
        ]);
        Empresa::create($validate);
        return redirect()->route('empresas.index')->withFlash('Dato guardado exitosamnete');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Empresa  $empresa
     * @return \Illuminate\Http\Response
     */
    public function show(Empresa $empresa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Empresa  $empresa
     * @return \Illuminate\Http\Response
     */
    public function edit(Empresa $empresa)
    {
         return view('empresas.views.edit',[
            'empresa' => $empresa
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Empresa  $empresa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Empresa $empresa)
    {
        if($request->ajax()){
            $validate = $this->validate($request,[
                'nombre_empresa' => 'required',
                'direccion_empresa' => 'required',
                'telefono_empresa' => 'required',
            ]);

            $empresa->update($validate);
            return response()->json([
                "mensaje" => "datos actualizados has sido actualizados con exito redirigir a <a href='http://www.directenglish.local/empresas'>Home</>"
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Empresa  $empresa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empresa $empresa)
    {
         $empresa->activate();
        return redirect()->route('empresas.index')->withFlash("El registro ha sido eliminado con exito");
    }
}

resources/views/empresas/views/create.blade.php
 @extends('empresas.layout')
 @section('content')
 <div class="alert alert-primary alert-dismissible fade show data-alert" role='alert' style="display: none;">
	{{-- {{ session('flash') }} --}}
	<button type="button" class="close" data-dismiss="alert" aria-label="close" >
		<span aria-hidden="true">&times;</span>
	</button>
</div>
 <form method="POST" action="{{ route('empresas.store') }}" id="saveforms">
  @csrf
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">

	      <h4 class="modal-title" id="myModalLabel">Creacion de un registro</h4>
	    </div>
	    <div class="modal-body">
	      <div class="form-group {{ $errors->has('nombre_empresa') ? 'has-error' : '' }}">
	        <input id="nombre" class="form-control" type="text" name="nombre_empresa" placeholder="ingrese el nombre de la empresa"
	        value="{{ old('nombre_empresa')}}" autofocus >
	        {!! $errors->first('nombre_empresa', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('direccion_empresa') ? 'has-error' : '' }}">
	        <input id="direccion_empresa" class="form-control" type="text" name="direccion_empresa" placeholder="ingrese la direccion de la empresa"
	        value="{{ old('direccion_empresa')}}" autofocus >
	        {!! $errors->first('direccion_empresa', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('telefono_empresa') ? 'has-error' : '' }}">
	        <input id="telefono_empresa" class="form-control" type="text" name="telefono_empresa" placeholder="ingrese el telefono del empleado"
	        value="{{ old('telefono_empresa')}}" autofocus >
	        {!! $errors->first('telefono_empresa', '<span class="help-block">:message</span>') !!}
	      </div>
	    </div>
	    <div class="modal-footer">
	      <button id="createpost"  onclick="saveproject()"  class="btn btn-primary">Crear publicacion</button>
	    </div>
	  </div>
	</div>
</form>
@endsection

resources/views/empresas/views/edit.blade.php
 @extends('empresas.layout')
 @section('content')
 <form method="POST" action="#" id="saveformsupdate">
  @csrf
  @method('PUT')
  <div class="alert alert-primary alert-dismissible fade show data-alert" role='alert' style="display: none;" >
		<button type="button" class="close" data-dismiss="alert" aria-label="close" >
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">

	      <h4 class="modal-title" id="myModalLabel">Editar un proyecto</h4>
	    </div>
	    <div class="modal-body">
	      <div class="form-group {{ $errors->has('nombre_empresa') ? 'has-error' : '' }}">
	        <input id="nombre" class="form-control" type="text" name="nombre_empresa" placeholder="ingrese el nombre de la empresa"
	        value="{{ old('nombre_empresa',$empresa->nombre_empresa)}}" autofocus >
	        {!! $errors->first('nombre_empresa', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('direccion_empresa') ? 'has-error' : '' }}">
	        <input id="direccion_empresa" class="form-control" type="text" name="direccion_empresa" placeholder="ingrese la direccion de la empresa"
	        value="{{ old('direccion_empresa',$empresa->direccion_empresa)}}" autofocus >
	        {!! $errors->first('direccion_empresa', '<span class="help-block">:message</span>') !!}
	      </div>

	      <div class="form-group {{ $errors->has('telefono_empresa') ? 'has-error' : '' }}">
	        <input id="telefono_empresa" class="form-control" type="text" name="telefono_empresa" placeholder="ingrese el telefono del empleado"
	        value="{{ old('telefono_empresa',$empresa->telefono_empresa)}}" autofocus >
	        {!! $errors->first('telefono_empresa', '<span class="help-block">:message</span>') !!}
	      </div>
	    </div>
	    <div class="modal-footer">
	      <button  class="btn btn-primary" onclick="actualizar({{ $empresa->id }})">Actualizar publicacion</button>
	    </div>
	  </div>
	</div>
</form>
@endsection

resources/views/empresas/views/index.blade.php
@extends('empresas.layout')
@section('content')
<div class="container">
		<div class="row">
              @if(session('flash'))
					<div class="alert alert-primary alert-dismissible fade show data-alert" role='alert' >
						{{ session('flash') }}
						<button type="button" class="close" data-dismiss="alert" aria-label="close" >
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				@endif
			<div class="mx-auto">
				CONTENIDO DE LA TABLA EMPRESAS
			</div>
		</div>
		<div class="row">
			<div class="mx-auto">
				<a  href="{{ route('empresas.create')}}">Crear una empresa</a>
				<table class="table">
					<tr>
						<td>ID_EMPLEADO</td>
						<td>NOMBRE</td>
						<td>DIRECCION</td>
						<td>TELEFONO</td>>
						<td>ACCIONES</td>
					</tr>
					@foreach($empresas as $empresa)
						<tr>
							<td>{{$empresa->id}}</td>
							<td>{{$empresa->nombre_empresa}}</td>
							<td>{{$empresa->direccion_empresa}}</td>
							<td>{{$empresa->telefono_empresa}}</td>
							<td>
								<a class="btn btn-xs  btn-primary" href="{{ route('empresas.edit',$empresa) }}">Editar</a>

								/
								<form id="saveformdelete" action="{{ route('empresas.destroy',$empresa) }}" method="POST" style="display: inline;">
				                @csrf @method('DELETE')
				                <button onclick="return confirm('Esta seguro de eliminar la prublicacion ?')"class="btn btn-xs  btn-danger">Eliminar</button>
				              </form>
							</td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
</div>
@endsection